artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Ramyasreekodati/FLIGHT_PRICE_PREDICTION/raw/refs/heads/main/research/cleaned_data_flight.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/WineQT.csv
  STATUS_FILE: artifacts/data_validation/status.txt